import sqlite3

# Task 3: Populate Tables with Data
def add_publishers(cursor, name):
    try:
        cursor.execute("INSERT INTO Publishers (name) VALUES (?)", (name,))
    except sqlite3.IntegrityError:
        print(f"{name} is already in the database.")

def add_magazines(cursor, name, publisher_id):
    try:
        cursor.execute("INSERT INTO Magazines (name, publisher_id) VALUES (?, ?)", (name, publisher_id))
    except sqlite3.IntegrityError as e:
        if "NOT NULL constraint failed" in str(e):
            print(f"Publisher_id cannot be NULL.")
        if "UNIQUE constraint failed" in str(e):
            print(f"{name} is already in the database.")
        if "FOREIGN KEY constraint failed" in str(e):
            print(f"Publisher_id {publisher_id} does not exist in the Publishers table.")

def add_subscribers(cursor, name, address):
    try:
        cursor.execute("INSERT INTO Subscribers (name, address) VALUES (?, ?)", (name, address))
    except sqlite3.IntegrityError as e:
        if "NOT NULL constraint failed" in str(e):
            print(f"Name cannot be NULL.")
        if "UNIQUE constraint failed" in str(e):
            print(f"{(name, address)} is already in the database.")

def add_subscriptions(cursor, subscriber_id, magazine_id, expiration_date):
    try:
        cursor.execute("INSERT INTO Subscriptions (subscriber_id, magazine_id, expiration_date) VALUES (?, ?, ?)", (subscriber_id, magazine_id, expiration_date))
    except sqlite3.IntegrityError as e:
        if "NOT NULL constraint failed" in str(e):
            print(f"Missing subscriber_id, magazine_id or expiration_date.")
        if "UNIQUE constraint failed" in str(e):
            print(f"{(subscriber_id, magazine_id, expiration_date)} is already in the database.")

def main():
    # Task 1: Create a New SQLite Database

    # Connect to the database
    try:
        with sqlite3.connect("../db/magazines.db") as conn:
            cursor = conn.cursor()

    except sqlite3.Error as e:
        print(f"An error occurred while connecting to the database: {e}")



    # Task 2: Define Database Structure

    # Adding the Publishers table
    try:
        cursor.execute("""
        CREATE TABLE IF NOT EXISTS Publishers (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL UNIQUE
        )
        """)
    except sqlite3.Error as e:
        print(f"An error occured while creating the Publishers table: {e}")

    # Add the Magazines table
    try:
        cursor.execute("""
        CREATE TABLE IF NOT EXISTS Magazines (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            publisher_id INT NOT NULL,
            FOREIGN KEY (publisher_id) REFERENCES publishers (id)
        )
        """)
    except sqlite3.Error as e:
        print(f"An error occured while creating the Magazines table: {e}")

    # Add the Subscribers table
    try:
        cursor.execute("""
        CREATE TABLE IF NOT EXISTS Subscribers (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            address TEXT NOT NULL,
            UNIQUE(name, address)
        )
        """)
    except sqlite3.Error as e:
        print(f"An error occured while creating the Subscribers table: {e}")
    
    # Add the Subscriptions table
    try:
        cursor.execute("""
        CREATE TABLE IF NOT EXISTS Subscriptions (
            id INTEGER PRIMARY KEY,
            subscriber_id INTEGER NOT NULL,
            magazine_id INTEGER NOT NULL,
            expiration_date TEXT NOT NULL,
            FOREIGN KEY (subscriber_id) REFERENCES Subscribers (id),
            FOREIGN KEY (magazine_id) REFERENCES Magazines (id),
            UNIQUE (subscriber_id, magazine_id, expiration_date)
        )
        """)
    except sqlite3.Error as e:
        print(f"An error occured while creating the Subscription table: {e}")

    # Task 3: Populate Tables with Data
    conn.execute("PRAGMA foreign_keys = 1") # This turns on the foreign key constraint

    # Sample data generated by Gemini
    publishers_data = [
        ('Global Media',),
        ('Tech Press',),
        ('Fashion Forward',)
    ]

    magazines_data = [
        ('World News Daily', 1),
        ('Cyber Security Today', 2),
        ('Vogue Edge', 3),
        ('Game Day Weekly', 1),
        ('Deep Space Exploration', 3),
        ('The 30-Minute Chef', 2),
        ('Hidden Trails', 2),
        ('Stock Market Insider', 2),
        ('Toy Box Monthly', 1),
        ('Forest & Stream', 3)
    ]

    subscribers_data = [
        ('Alice Smith', '123 Pine St'),
        ('Bob Jones', '456 Oak Ave'),
        ('Charlie Brown', '789 Maple Ln'),
        ('Diana Prince', '101 Amazon Way'),
        ('Ethan Hunt', '555 Mission St'),
        ('Fiona Apple', '222 Orchard Rd'),
        ('George King', '333 Castle Blvd'),
        ('Hannah Abbott', '444 Hufflepuff Dr'),
        ('Ian Wright', '777 Arsenal Ct'),
        ('Julia Roberts', '888 Hollywood Blvd')
    ]

    subscriptions_data = [
        (1, 1, 'October 8, 2026'),
        (1, 2, 'February 14, 2027'),
        (2, 2, 'July 29, 2028'),
        (3, 3, 'April 3, 2029'),
        (4, 4, 'January 7, 2038'),
        (5, 5, 'August 19, 2035'),
        (6, 6, 'May 22, 2033'),
        (7, 7, 'September 30, 2040'),
        (8, 8, 'December 25, 2046'),
        (9, 9, 'November 12, 2031'),
        (1, 3, 'June 15, 2043'),
        (5, 2, 'September 18, 2055'),
        (4, 5, 'March 11, 2050')
    ]

    for p in publishers_data:
        add_publishers(cursor, *p)
    
    for m in magazines_data:
        add_magazines(cursor, *m)
    
    for s in subscribers_data:
        add_subscribers(cursor, *s)

    for ss in subscriptions_data:
        add_subscriptions(cursor, *ss)

    # Some test case by Gemini
    # add_publishers(cursor, 'Global Media') # Should throw the IntegrityError for duplicate
    # add_subscribers(cursor, 'Alice Smith', '123 Pine St') # Should throw the IntegrityError for duplicate
    # add_magazines(cursor, 'Ghost Magazine', 99) # Should throw IntegrityError because of the Foreign Key
    # add_subscriptions(cursor, 1, 1, 'October 8, 2026') # Should throw the IntegrityError for duplicate
    
    # Commit the change
    conn.commit()
    


    # Task 4: Write SQL Queries

    queries = [
        """
        SELECT * FROM Subscribers;
        """,
        """
        SELECT * FROM Magazines
        ORDER BY name;
        """,
        """
        SELECT p.name as Publisher_name, m.name as Magazine_name FROM Publishers as p
        LEFT JOIN Magazines as m
        ON m.Publisher_id = p.id
        WHERE p.name = "Global Media";
        """
    ]
    print()
    print('Extracting data from database:')
    for q in queries:
        try:
            cursor.execute(q)
            results = cursor.fetchall()
            for row in results:
                print(row)
            print()
        except sqlite3.Error as e:
            print(f"SQL Error: {e}")



    # Disconnect from the database
    try:
        conn.close()
    except sqlite3.Error as e:
        print(f"An error occurred while closing the database connection: {e}")

if __name__ == '__main__':
    main()